<?php

/**
 * @file
 * Hooks for uc_quickpay module
 */

use Drupal\uc_order\Entity\Order;

/**
* Implements hook_quickpay_callback().
*/
function uc_quickpay_quickpay_callback($order_id, $transaction) {
  \Drupal::logger('uc_quickpay')
    ->info('Transaction callback for order ID: !id', array('!id' => $order_id));
  $order = Order::load($order_id);
  if ($transaction->approved) {
    // Load the order and set the transaction ID.
    if (abs($transaction->amount - $order->getTotal()) > 0.01) {
      \Drupal::logger('uc_quickpay')
        ->warning(
          'Quickpay payment @txn_id for order @order_id did not equal the order total.',
          [
            '@txn_id' => $transaction->id,
            '@order_id' => $order->id(),
            'link' => Link::createFromRoute(t('view'), 'entity.uc_order.canonical', ['uc_order' => $order->id()])
              ->toString()
          ]
        );
    }
    $comment = $this->t('Quickpay transaction ID: @txn_id', ['@txn_id' => $transaction->id]);
    uc_payment_enter($order_id, 'quickpay', $transaction->amount, $order->getOwnerId(), $transaction, $comment);
    uc_order_comment_save(
      $order_id,
      0,
      t('Quickpay reported a payment/authorization of @amount @currency.', [
        '@amount' => uc_currency_format($transaction->amount, FALSE),
        '@currency' => $transaction->currency
      ])
    );
  }
}