<?php

/**
 * @file
 * Hooks for uc_quickpay module
 */

use Drupal\uc_order\Entity\Order;
use Drupal\Core\Link;

/**
* Implements hook_quickpay_callback().
*/
function uc_quickpay_quickpay_callback($order_id, $transaction) {
  \Drupal::logger('uc_quickpay')
    ->info('Transaction callback for order ID: @id', array('@id' => $order_id));
  $order = Order::load($order_id);
  // Check if we already registered payment - this can unfortunately happen
  // that Quickpay tries to deliver confirmation asynchronously multiple times
  if ($order->getStatusId() == 'payment_received') {
    \Drupal::logger('uc_quickpay')
      ->notice(
        'Payment callback for order @order from Quickpay (transaction: @txn_id) but already marked as paid.',
        ['@order' => $order->id(), '@txn_id' => $transaction->id]
      );
    return;
  }
  if ($transaction->approved) {
    // Load the order and set the transaction ID.
    if (abs($transaction->amount - $order->getTotal()) > 0.01) {
      \Drupal::logger('uc_quickpay')
        ->warning(
          'Quickpay payment @txn_id for order @order_id did not equal the order total.',
          [
            '@txn_id' => $transaction->id,
            '@order_id' => $order->id(),
            'link' => Link::createFromRoute(t('view'), 'entity.uc_order.canonical', ['uc_order' => $order->id()])
              ->toString()
          ]
        );
    }
    $comment = t('Quickpay transaction ID: @txn_id', ['@txn_id' => $transaction->id]);
    uc_payment_enter($order_id, 'quickpay', $transaction->amount, $order->getOwnerId(), $transaction->getData(), $comment);
    uc_order_comment_save(
      $order_id,
      0,
      t('Quickpay reported a payment/authorization of @amount @currency.', [
        '@amount' => uc_currency_format($transaction->amount, FALSE),
        '@currency' => $transaction->currency
      ]),
      'admin',
      'payment_received'
    );
    \Drupal::logger('uc_quickpay')
      ->info('Done registering Quickpay payment.');
  }
  else {
    \Drupal::logger('quickpay')->warning('Not-approved transaction from Quickpay: @transaction.', array('@transaction' => print_r($transaction, TRUE)));
  }
}