<?php
/**
 * @file
 * Module for testing/debugging the Quickpay payment window.
 */

/**
 * Implements hook_quickpay_callback().
 */
function quickpay_example_quickpay_callback($order_id, $transaction) {
  if ($transaction->approved) {
    // Load the order node and set the transaction ID.
    $nids = \Drupal::entityQuery('node')
      ->condition('field_example_order_id', $order_id)
      ->execute();
    $nid = array_pop($nids);
    $node = node_load($nid);
    if ($node) {
      $node->set('field_example_transaction_id', $transaction->id);
      $node->save();
    }
    \Drupal::logger('quickpay_test')->info('Transaction not approved for order ID: !id', array('!id' => $order_id));
  }
  else {
    \Drupal::logger('quickpay_test')->info('Transaction not approved for order ID: !id', array('!id' => $order_id));
  }
}
