<?php
/**
 * @file
 * Module for testing/debugging the Quickpay payment window.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_quickpay_callback().
 */
function quickpay_example_quickpay_callback($order_id, $transaction) {
  if ($transaction->approved) {
    // Load the order node and set the transaction ID.
    $node = Node::load($order_id);
    if ($node) {
      $node->set('field_example_transaction_id', $transaction->id);
      $node->save();
    }
    \Drupal::logger('quickpay_test')->info('Transaction approved for order ID: @id', array('@id' => $order_id));
  }
  else {
    \Drupal::logger('quickpay_test')->info('Transaction not approved for order ID: @id', array('@id' => $order_id));
  }
}
